//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBRD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutContentService
    {
        public int ServiceID { get; set; }
        public Nullable<int> AboutContentID { get; set; }
        public string Service { get; set; }
    
        public virtual AboutContent AboutContent { get; set; }
    }
}
