//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBRD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutContent
    {
        public AboutContent()
        {
            this.AboutContentServices = new HashSet<AboutContentService>();
        }
    
        public int ID { get; set; }
        public string ImageFile { get; set; }
        public string Heading { get; set; }
        public string Paragraph { get; set; }
    
        public virtual ICollection<AboutContentService> AboutContentServices { get; set; }
    }
}
