//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBRD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambulance
    {
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleName { get; set; }
        public string VehicleOwnerName { get; set; }
        public Nullable<int> Driver_Id { get; set; }
        public Nullable<int> VehicleCat_Id { get; set; }
        public Nullable<int> VehicleType_Id { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
        public Nullable<System.DateTime> InsurranceDate { get; set; }
        public Nullable<System.DateTime> PollutionDate { get; set; }
        public Nullable<double> DriverCharges { get; set; }
        public string VehicleImg { get; set; }
        public string CancelChequeFile { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string HolderName { get; set; }
        public string RCImage { get; set; }
        public Nullable<System.DateTime> RC_Validity { get; set; }
        public string RC_Number { get; set; }
    }
}
