//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBRD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> AdminLogin_Id { get; set; }
        public string PatientRegNo { get; set; }
        public string Password { get; set; }
        public string PatientName { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> StateMaster_Id { get; set; }
        public Nullable<int> CityMaster_Id { get; set; }
        public string Location { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public Nullable<double> walletAmount { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
