//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBRD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string VehicleTypeName { get; set; }
        public Nullable<int> VehicleCatId { get; set; }
        public Nullable<double> under0_2KM { get; set; }
        public Nullable<double> under3_8KM { get; set; }
        public Nullable<double> under9_15KM { get; set; }
        public Nullable<double> under16_25KM { get; set; }
        public Nullable<double> under26_40KM { get; set; }
        public Nullable<double> under41_60KM { get; set; }
        public Nullable<double> under61_80KM { get; set; }
        public Nullable<double> under81_110KM { get; set; }
        public Nullable<double> under111_150KM { get; set; }
        public Nullable<double> under151_200KM { get; set; }
        public Nullable<double> under201_250KM { get; set; }
        public Nullable<double> under251_300KM { get; set; }
        public Nullable<double> under301_350KM { get; set; }
        public Nullable<double> under401_450KM { get; set; }
        public Nullable<double> under451_500KM { get; set; }
        public Nullable<double> Above500KM { get; set; }
        public string VehicleImage { get; set; }
    }
}
